---
output:
html_document:
self_contained: false
lib_dir: "libs"
fig_height: 2
fig_width: 4
params:
element: "dolphins"
---

```{r, echo=FALSE, message=F, warning=F}
knitr::opts_chunk$set(echo=F, message=F, warning=F)
library(infographiq)
```

<base target="_parent">
**Bottlenose Dolphins (*Tursiops truncatus*)**

In the Gulf of Mexico, bottlenose dolphins are split into two distinct groups, coastal and offshore. Coastal bottlenose dolphins are smaller in size than the offshore group, and likely do not interbreed. They are a common saltmarsh resident in Louisiana, where they travel up saltmarsh bayous and canals to fish. Bottlenose dolphins have strong site fidelity and will not leave the area where they’re born. Thus, coastal Louisiana populations are reliant on healthy coastal marshes for survival.

At least 900 bottlenose dolphins died as a direct result of the Deepwater Horizon oil spill in 2010, but the disaster’s overall impact on the coastal population isn’t well known. There was little bottlenose dolphin monitoring prior to the spill in Louisiana , which makes it difficult to make any before and after comparisons of the population. However, bottlenose dolphins in coastal areas directly affected by oiling have been found to have serious health problems such as liver and respiratory diseases. Studies with these findings indicate that oil exposure may therefore have had damaging long-term effects on the Louisiana population. Settlement money from the spill is being used to finding new ways to monitor bottlenose dolphins in the Gulf of Mexico. One promising approach is the use of underwater acoustic recording to identify the Gulf’s 13 dolphin species through their echolocation clicks, which differ between species. Such data could potentially be used to estimate population sizes. 

**References**: Gulf Spill Restoration. Study by NOAA and Partners Shows Some Gulf Dolphins Severely Ill. [link]
(http://www.gulfspillrestoration.noaa.gov/2012/03/study-shows-some-gulf-dolphins-severely-ill)


Frasier, K. E., M.A. Roch, M.S. Soldevilla, S.M. Wiggins, L.P Garrison, and J.A. Hildebrand. 2017. Automated classification of dolphin echolocation click types from the Gulf of Mexico. PLoS Comput Biol 13(12): e1005823. https://doi.org/10.1371/journal.pcbi.1005823
