---
output:
html_document:
self_contained: false
lib_dir: "libs"
fig_height: 2
fig_width: 4
params:
element: "fiddlercrabs"
---

```{r, echo=FALSE, message=F, warning=F}
knitr::opts_chunk$set(echo=F, message=F, warning=F)
library(infographiq)
```

<base target="_parent">
**Fiddler Crab (*Minuca* spp.)**

Fiddler crabs in the Gulf of Mexico managed to withstand the Deepwater Horizon oil spill, but the spill likely negatively affected their resilience to withstand future damages to the marsh ecosystem. Louisiana’s coastal marshes are home to several species of fiddler crabs of the *Minuca* (formerly *Uca*) genus. Fiddler crabs are marsh ecosystem engineers that shape the environment around them. They live in large colonies, and their densely crowded burrows help aerate the soil. The oxygen the crabs draw into the soil aids respiration of marsh grasses and other plants. Fiddler crabs eat bacteria and decaying plant material, helping keep marsh waters clean. They’re also an important food source for many species. Because they feed so low on the food chain, fiddler crabs are very susceptible to input of toxins such as heavy metals from events like the 2010 spill. As a prey species, they then pass these concentrated toxins on to their predators, leading to the spread of contaminants across the food web. 

A study conducted following the 2010 Deepwater Horizon oil spill found that fiddler crab burrow density and diameter were both reduced in oiled versus unoiled coastal marsh sites, and that species composition similarly declined. Fiddler crab populations in the region appeared to have fully recovered by 2013. However, results from this study indicate that oil spills have the potential to greatly affect coastal marsh ecosystem functioning by suppressing populations of foundational species like fiddler crabs.

**Reference**: Zengel, S. et al. 2016. *Deepwater Horizon* oil spill impacts on salt marsh fiddler crabs (*Uca* spp.) Estuaries and Coasts 39: 1154-1163.
 
