---
output:
html_document:
self_contained: false
lib_dir: "libs"
fig_height: 2
fig_width: 4
params:
element: "nutria"
---

```{r, echo=FALSE, message=F, warning=F}
knitr::opts_chunk$set(echo=F, message=F, warning=F)
library(infographiq)
```

<base target="_parent">


```{r out.width='100%'}
tryCatch(
    plot_dygraph_timeseries(
        csv_tv  = "https://github.com/mhepner90/LUMCON_ODOTCOMM18/blob/master/prep/data/nutria_summarized.csv",
        title   = "Annual Nutria Harvest",
        y_label = "Number of Tails Collected",
        col_t   = "Year",
        col_y   = "Tails_Collected"
        #skip_lines
        #group_by  
        #std_err   
        #filter
    ),
    error = function(e) e
)
```


```{r out.width='100%'}
tryCatch(
    plot_dygraph_timeseries(
        csv_tv  = "https://github.com/mhepner90/LUMCON_ODOTCOMM18/blob/master/prep/data/nutria_summarized.csv",
        title   = "NA",
        y_label = "Estimated Herbivory Damage (acres)",
        col_t   = "Year",
        col_y   = "Estimated_Herbivory_Damage_acres"
        #skip_lines
        #group_by  
        #std_err   
        #filter
    ),
    error = function(e) e
)
```
