---
output:
html_document:
self_contained: false
lib_dir: "libs"
fig_height: 2
fig_width: 4
params:
element: "snails"
---

```{r, echo=FALSE, message=F, warning=F}
knitr::opts_chunk$set(echo=F, message=F, warning=F)
library(infographiq)
```

<base target="_parent">
**Periwinkle snail (*Littoraria irrorata*)**

While commercial species in the Gulf of Mexico are generally monitored, we know little about marsh species that have no direct economic value. Such species may be less vital for the economy but may directly affect the healthy marsh functioning that is needed to maintain commercially-fished species. Periwinkle snails depend on damp marsh conditions to keep their gills wet but migrate up tall marsh grasses above the tideline to avoid predation. They form an important part of the marsh food web, with important predators including diamondback terrapins, blue crabs, and many of the Gulf of Mexico’s declining wading birds. Periwinkle snails contribute to marsh functioning, but have the potential to accelerate marsh land loss through overconsumption of smooth cordgrass if populations are not kept in check through predation. The effects of the oil spill on periwinkle snails is not understood, but, as with fiddler crabs, they may contribute to the spread of concentrated toxins through the food web. 
