---
output:
html_document:
self_contained: false
lib_dir: "libs"
fig_height: 2
fig_width: 4
params:
element: "tern"
---

```{r, echo=FALSE, message=F, warning=F}
knitr::opts_chunk$set(echo=F, message=F, warning=F)
library(infographiq)
```

<base target="_parent">
**Forster’s Tern (*Sterna forsteri*)**

As Louisiana’s coastal marshes disappear, the need to learn more about the species that rely on them becomes more urgent. Highlighting the gaps in our knowledge along with the trajectories of more well-studied species can provide an important blueprint for research planning. Not much is known about Forster’s terns in Louisiana despite their status as a species of conservation concern, representing an opportunity for valuable future research. Forster’s terns are a resident species in the state’s coastal marshes, where they plunge dive for fish and small arthropods over open water and canals. They are colonial, and sometimes nest on mats of floating marsh vegetation or on top of muskrat lodges. 
