---
output:
html_document:
self_contained: false
lib_dir: "libs"
fig_height: 2
fig_width: 4
params:
element: "terrapin"
---

```{r, echo=FALSE, message=F, warning=F}
knitr::opts_chunk$set(echo=F, message=F, warning=F)
library(infographiq)
```

<base target="_parent">
**Diamondback Terrapin (*Malaclemys terrapin*)**

Diamondback terrapins are the only turtles in North America that live exclusively in coastal habitats, and they have many unique adaptations for life in salt water. They are most commonly found in smooth cordgrass-dominated marshes. There, they emerge in early summer to lay eggs in nests dug into sandy dunes. Diamondback terrapins eat mollusks, crabs, and shrimp, and may help keep marshes healthy through consumption of periwinkle snails, which can overgraze smooth cordgrass when populations are left unchecked.

Louisiana has the most potential diamondback terrapin habitat in the country, but the species is not well-studied, and population trends are unknown. They’re a species of greatest conservation concern in the state as they were hunted almost to extinction due to their role as a key ingredient in turtle soup, which was a popular dish nationwide in the early half of the twentieth century. In more recent years, the nationwide popularity of turtle soup has waned, and current threats to diamondback terrapins include coastal land loss and human activity at nest sites. Abandoned blue crab traps are also a major cause of mortality. Diamondback terrapins enter the traps to feed on the bait and, unable to escape, drown in the traps. Adding Terrapin Excluder Devices (TEDs) to crab traps can help reduce the risk. Managers across the Gulf of Mexico are working to encourage use of these live-saving devices. 

**Reference**: Pearson, S. 2018. Evaluation of diamondback terrapin (*Malaclemys terrapin*) nesting ecology throughout coastal Louisiana. Terrapins and Crabs Special Session: 68th Annual Meeting of the Gulf States Marine Fisheries Commission. (https://www.gsmfc.org/ann_mtgs/2017-10/Gen_Sess/3.%20Terrapin%20Nesting%20in%20LA%20-%2010-16-17.pdf)
